#!/usr/bin/env python3
"""Create the gitignored per-device Wi-Fi and API credentials."""

from __future__ import annotations

import argparse
import getpass
import os
from pathlib import Path
import secrets
import sys


ROOT = Path(__file__).resolve().parents[2]
PROJECT = ROOT / "src/native"
OUTPUT = PROJECT / "services" / "remote_config.h"


def c_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Provision the Wi-Fi network and token the pedal uses in maintenance mode."
    )
    parser.add_argument("--ssid", help="the Wi-Fi network the pedal joins (prompted when omitted)")
    parser.add_argument(
        "--force", action="store_true", help="replace existing credentials (requires reflashing)"
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    # The prebuild writes a disabled stub when no file exists (see
    # scripts/pack-factory-assets.mjs); that carries no credentials to protect.
    is_stub = OUTPUT.exists() and "COYOPEDAL_REMOTE_STUB" in OUTPUT.read_text(encoding="utf-8")
    if OUTPUT.exists() and not is_stub and not args.force:
        print(f"{OUTPUT} already exists; use --force only when intentionally rotating credentials.")
        return 2

    ssid = args.ssid or input("Wi-Fi SSID: ").strip()
    if not ssid:
        print("A Wi-Fi SSID is required.", file=sys.stderr)
        return 2
    password = getpass.getpass("Wi-Fi password: ")

    if len(ssid.encode()) > 24:
        print("SSID must be 24 UTF-8 bytes or fewer.", file=sys.stderr)
        return 2
    if any(ord(character) < 32 or character in '"\\' for character in ssid):
        print(
            "SSID may not contain control characters, quotes, or backslashes.",
            file=sys.stderr,
        )
        return 2
    try:
        password_bytes = password.encode("ascii")
    except UnicodeEncodeError:
        password_bytes = b""
    if not 8 <= len(password_bytes) <= 63 or any(
        byte < 32 or byte > 126 for byte in password_bytes
    ):
        print("Wi-Fi password must contain 8-63 printable ASCII characters.", file=sys.stderr)
        return 2

    token = secrets.token_hex(32)
    text = f'''#pragma once

// Generated by tools/configure_remote.py. This file is gitignored.
#define COYOPEDAL_REMOTE_ENABLED 1
#define COYOPEDAL_REMOTE_DISABLE_USB_AUDIO 0
#define COYOPEDAL_REMOTE_WIFI_SSID "{c_string(ssid)}"
#define COYOPEDAL_REMOTE_WIFI_PASSWORD "{c_string(password)}"
#define COYOPEDAL_REMOTE_TOKEN "{token}"
'''
    OUTPUT.write_text(text)
    os.chmod(OUTPUT, 0o600)
    print(f"Wrote {OUTPUT}")
    print("Credentials stored locally. Use amoled_remote.py discover after flashing.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
